# Generated by Django 4.2 on 2023-04-22 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankBalance', models.BigIntegerField(default=0)),
                ('bankName', models.CharField(blank=True, max_length=255, null=True)),
                ('userObj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EUD_userObj', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('transactionType', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=255)),
                ('date', models.DateField(null=True)),
                ('amount', models.BigIntegerField(null=True)),
                ('userObj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EE_userObj', to='ExpenseSheet.expenseuserdata')),
            ],
        ),
    ]
